#ifndef __PACMAN_MAZE_H
#define __PACMAN_MAZE_H

#include "pacman_types.h"

// clang-format off
const PM_MazeObj PACMAN_BaseMaze[PM_MAZE_SCALED_HEIGHT][PM_MAZE_SCALED_WIDTH] = {
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},    
    {PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_WALL, PM_WALL, PM_NONE, PM_WALL, PM_WALL, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_LTPL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_NONE, PM_NONE, PM_WALL, PM_NONE, PM_GHSR, PM_NONE, PM_WALL, PM_NONE, PM_NONE, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_RTPL},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_PCMN, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_NONE, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
};
// clang-format on

#endif