// This image array was auto-generated by img2c.py. Do not edit it manually.
#ifndef __PACMAN_YELLOWGHOST_H
#define __PACMAN_YELLOWGHOST_H

#include "glcd_types.h"
#include "types.h"


// clang-format off

const u32 Image_PACMAN_YellowGhostData[] = {
	1, 0x000000,
	1, 0x524214,
	1, 0xC9A42C,
	1, 0xF5C733,
	1, 0xF4C634,
	1, 0xC6A22C,
	1, 0x4C3D13,
	1, 0x000000,
	1, 0x645118,
	1, 0xF8C931,
	1, 0xFFD335,
	1, 0xFFD135,
	1, 0xFFCC30,
	1, 0xFFD132,
	1, 0xFCCF39,
	1, 0x5A4916,
	1, 0xE7B92E,
	1, 0xFFDA54,
	1, 0xE4DCBF,
	1, 0xC2A959,
	1, 0xFED036,
	1, 0xF8E9B4,
	1, 0xBCAF7B,
	1, 0xD6AF34,
	1, 0xFAC830,
	1, 0xFFD652,
	1, 0xE6DCBA,
	1, 0xC6AD5A,
	1, 0xFFD036,
	1, 0xF8E8B0,
	1, 0xBFAF7A,
	1, 0xEDC035,
	1, 0xF8C833,
	1, 0xFFCB30,
	1, 0xFFCD32,
	1, 0xFFD034,
	1, 0xFECB31,
	1, 0xFECC2F,
	1, 0xFFD235,
	1, 0xF1C231,
	1, 0xF8C833,
	1, 0xFFCD32,
	1, 0xFFD333,
	2, 0xFFCD32,
	1, 0xFFD334,
	1, 0xFFCE32,
	1, 0xF1C331,
	1, 0xF6C734,
	1, 0xF0C131,
	1, 0x876C1F,
	1, 0xF4C532,
	1, 0xF0C131,
	1, 0x866C1F,
	1, 0xF5C531,
	1, 0xEDBF32,
	1, 0xA98828,
	1, 0x957823,
	1, 0x000000,
	1, 0x9F8125,
	1, 0x947723,
	1, 0x000000,
	1, 0xA08125,
	1, 0x9D7F25,
};

// clang-format on

const LCD_Image Image_PACMAN_YellowGhost = {
    .pixels = Image_PACMAN_YellowGhostData, .width = 8, .height = 8, .has_alpha = false};

#endif