// This image array was auto-generated by img2c.py. Do not edit it manually.
#ifndef __PACMAN_PINKGHOST_H
#define __PACMAN_PINKGHOST_H

#include "glcd_types.h"
#include "types.h"


// clang-format off

const u32 Image_PACMAN_PinkGhostData[] = {
	1, 0x000000,
	1, 0x321E28,
	1, 0xA06382,
	2, 0xD382AB,
	1, 0x9D617F,
	1, 0x2E1C25,
	1, 0x000000,
	1, 0x4C2F3D,
	1, 0xEB8FBE,
	1, 0xFF9FD3,
	1, 0xFF9FD2,
	1, 0xFF9CCF,
	1, 0xFF9DD2,
	1, 0xEE92C0,
	1, 0x452A37,
	1, 0xDB84AF,
	1, 0xFFACD9,
	1, 0xE9CFDB,
	1, 0xCC94B0,
	1, 0xFF9DCF,
	1, 0xF8D1E4,
	1, 0xCAA3B7,
	1, 0xCD80A6,
	1, 0xF694C4,
	1, 0xFFACD6,
	1, 0xE3D3DC,
	1, 0xC08FA7,
	1, 0xFF9ED0,
	1, 0xF7D8E8,
	1, 0xB89AA9,
	1, 0xE990BC,
	1, 0xF495C4,
	1, 0xFF99CC,
	1, 0xFF9CCE,
	1, 0xFF9ED1,
	1, 0xFF99CB,
	1, 0xFF9ACC,
	1, 0xFFA1D3,
	1, 0xEE91BE,
	1, 0xF595C5,
	1, 0xFF9BCE,
	1, 0xFF9FD3,
	1, 0xFF9BCD,
	1, 0xFF9BCE,
	1, 0xFF9FD3,
	1, 0xFF9CCE,
	1, 0xEE91BF,
	1, 0xF193C1,
	1, 0xF092C1,
	1, 0x7B4B62,
	1, 0xF293C1,
	1, 0xED90BE,
	1, 0x7B4B63,
	1, 0xF494C4,
	1, 0xE98EBB,
	1, 0x905974,
	1, 0x89546D,
	1, 0x000000,
	1, 0x8B5570,
	1, 0x845169,
	1, 0x000000,
	1, 0x905873,
	1, 0x89536D,
};

// clang-format on

const LCD_Image Image_PACMAN_PinkGhost = {
    .pixels = Image_PACMAN_PinkGhostData, .width = 8, .height = 8, .has_alpha = false};

#endif