// This image array was auto-generated by img2c.py. Do not edit it manually.
#ifndef __PACMAN_REDGHOST_H
#define __PACMAN_REDGHOST_H

#include "glcd_types.h"
#include "types.h"


// clang-format off

const u32 Image_PACMAN_RedGhostData[] = {
	1, 0x000000,
	1, 0x280202,
	1, 0x9A0202,
	2, 0xD20202,
	1, 0x9A0202,
	1, 0x290101,
	1, 0x000000,
	1, 0x380202,
	1, 0xE10000,
	4, 0xFF0000,
	1, 0xE60101,
	1, 0x390101,
	1, 0xBD0101,
	1, 0xFF1818,
	1, 0xE9A2A2,
	1, 0xC84242,
	1, 0xFD0808,
	1, 0xF39493,
	1, 0xCB5E5D,
	1, 0xBA0606,
	1, 0xDE0101,
	1, 0xFE1E1E,
	1, 0xE5B6B6,
	1, 0xBB4846,
	1, 0xFD0A0A,
	1, 0xF2A8A8,
	1, 0xB86565,
	1, 0xD90707,
	1, 0xDC0303,
	1, 0xFF0000,
	1, 0xFD0101,
	1, 0xFF0303,
	1, 0xFD0000,
	1, 0xFC0000,
	1, 0xFF0404,
	1, 0xDB0202,
	1, 0xDD0203,
	6, 0xFF0000,
	1, 0xDC0302,
	1, 0xD50302,
	1, 0xF70101,
	1, 0x7D0303,
	1, 0xEA0101,
	1, 0xEB0101,
	1, 0x7D0303,
	1, 0xF60101,
	1, 0xD50302,
	1, 0x750303,
	1, 0x970303,
	1, 0x000101,
	2, 0x830303,
	1, 0x000101,
	1, 0x960303,
	1, 0x760303,
};

// clang-format on

const LCD_Image Image_PACMAN_RedGhost = {
    .pixels = Image_PACMAN_RedGhostData, .width = 8, .height = 8, .has_alpha = false};

#endif